name: Metrics
on:
  # Schedule monthly updates
  schedule: [{cron: "0 0 1 * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # show activity over time
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          # show changed lines
          # plugin_lines: yes
          # plugin_lines_delay: 30

